---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Create .ssh folder in the users home folder (for github actions).
      file:
        path: "~/.ssh/"
        mode: '0700'
        state: directory
      delegate_to: localhost
      tags:
        - molecule-idempotence-notest

    - name: Ensure needed ssh keypair is created.
      openssh_keypair:
        path: "~/.ssh/id_rsa"
      delegate_to: localhost
      tags:
        - molecule-idempotence-notest

    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install OpenSSH.
      apt:
        name: openssh-server
      tags:
        - molecule-idempotence-notest

    - name: Create /var/run/sshd directory.
      file:
        path: /var/run/sshd
        state: directory
      tags:
        - molecule-idempotence-notest

  tasks:
    - name: Include "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}".
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
