---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install OpenSSH.
      apt:
        name: openssh-server

    - name: Create /var/run/sshd directory.
      file:
        path: /var/run/sshd
        state: directory
      tags:
        - molecule-idempotence-notest

    - name: Ensure needed ssh keys are created.
      openssh_keypair:
        path: "~/.ssh/id_rsa"
      delegate_to: localhost

  tasks:
    - name: Include "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}".
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
